server:
  port: 9999
spring:
  application:
    name: plant-gateway-service
  cloud:
    gateway:
      routes: 
      - id: plant-account-service
        uri: lb://plant-account-service
        predicates: 
        - Path=/account/**
      - id: plant-service
        uri: lb://plant-service
        predicates:
        - Path=/plants/**
      - id: plant-order-service
        uri: lb://plant-order-service
        predicates: 
        - Path=/order/**
        filters:
          - name: CircuitBreaker
            args: 
              name: plant-order-service
              fallbackUri: forward:/orderFallback
      - id: plant-payment-service
        uri: lb://plant-payment-service
        predicates: 
        - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
# enabling endpoints for springboot actuator health and gateway stats
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
