server:
  port: 9999
spring:
  application:
    name: plant-gateway-service
  cloud:
    gateway:
      routes: 
      - id: plant-account-service
        uri: lb://plant-account-service
        predicates: 
        - Path=/account/**
      - id: plant-service
        uri: lb://plant-service
        predicates:
        - Path=/plants/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost