server: 
  port: 4444
spring: 
  application:
    name: plant-payment-service
  datasource:
    uri: jdbc:h2:mem:paymentdb
    username: sa 
    password: sa 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
  h2: 
    console:
      enabled: true
eureka: 
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka